### ISSUE TITLE
v2 只有 100M 版本吗？

### ISSUE THREAD

**Issue by dufu1991** [amzxyz/RIME-LMDG#6]
v2 只有 100M 版本吗？

是不是文件越大效果越好？我想要最好的效果，但是 v2 没有 300M 版本。

**Comment by amzxyz** [comment]
也不是绝对的，你可以都测试一下，说到底要看数据结构与你自身是否匹配

**Comment by wxyzh** [comment]
@amzxyz 请问下模型需要和这个仓库的字典配合吗？
按我的理解，模型里是只有词和频并无编码。
另外模型中的词条最大长度是5还是8?

**Comment by amzxyz** [comment]
目前得模型适配的是白霜拼音的词库体验是最好的，我新建立得词库还存在很多问题包括读音上面得和词频上面得问题，由于词库和模型实际上是强关联的，模型能顶1000万条词条，但是没了基础词库会让成词结构出现问题，二者的词频也会互补作用，因为模型只能依靠大数据，但是词库可以人工干预，最终获得满意的结果，最大可以设置为8

**Comment by dufu1991** [comment]
我建议 README 可以再多写一点，像我这种小白用户，不知道下载什么好。介绍一下简单的知识点，对比一下，我们就知道下载哪个版本了。

**Comment by wxyzh** [comment]
rime的模型体现的是多个词连续出现的频率。词库是单个词的编码和频率。
词库的频率也是依赖大数据，词库的话只能人工筛选分词。并不能直接调整词库的词频。
最好的结果是，模型、词库都使用相同的语料。

**Comment by wxyzh** [comment]
> 我建议 README 可以再多写一点，像我这种小白用户，不知道下载什么好。介绍一下简单的知识点，对比一下，我们就知道下载哪个版本了。
```
__include: octagram   #启用语言模型
#语言模型
octagram:
  __patch:
    grammar:
      language: amz-v2n3m1-zh-hans  
      collocation_max_length: 5
      collocation_min_length: 2
    translator/contextual_suggestions: true
    translator/max_homophones: 7
    translator/max_homographs: 7
```
这一段贴到当前的方案中。


下载模型到rime的用户目录，```language: amz-v2n3m1-zh-hans ``` 改成你下载的文件名（不包含后缀）
